### PR TITLE
Require Node.js 4, cleanup, support symbol functions

### PR DESCRIPTION
**Pull request by novemberborn**
Highlights:

* **Breaking** require Node.js 4
* Convert to ES2015, use `standard`
* Bring back Travis and AppVeyor
* Correctly handle symbol functions, e.g. `Symbol.iterator`. See https://github.com/avajs/ava/issues/1269

### CODE REVIEW

**Comment by novemberborn** [comment]
Rebased, now with correct CI config.

**Comment by sindresorhus** [comment]
@isaacs Any opinion on this?

**Comment by isaacs** [comment]
I prefer not mixing stylistic changes and functional changes, and try to avoid stylistic changes at all unless they provide functional benefits.

In this case, I don't see much benefit to dropping support for older nodes before making the fix in https://github.com/tapjs/stack-utils/pull/27/commits/4e1a9065b04ac1d5a36a46ae263a90960e9279c8, especially since that would mean that tap 10 and earlier could never pull in this fix.

Please rebase https://github.com/tapjs/stack-utils/pull/27/commits/4e1a9065b04ac1d5a36a46ae263a90960e9279c8 onto current master, with current master's style.  That is a good bugfix which should be applied as a patch release asap.

I'd prefer not to add standard, or switch from tabs to spaces.  Switching to node 4+ style const/let/arrow functions/classes is fine, but ought to be separated from the bugfix, because it's a major version bump.

Adding CI files is great, and should also come ahead of any stylistic changes.

**Comment by novemberborn** [comment]
> I prefer not mixing stylistic changes and functional changes

To be fair, while these are in the same PR they are in separate commits. I assume you want them in different PRs, so I'll do that. Unfortunately they still kinda depend on each other.

> I'd prefer not to add standard, or switch from tabs to spaces.

Well you switched to spaces in https://github.com/tapjs/stack-utils/commit/c735f3cb3ffd44018c7838bf14349fe0b4145140. Since that also removed XO I figured I'd add `standard` as a linter instead. But fine, opened a PR that just fixes `.editorconfig` (since otherwise editing creates inconsistencies): #29.

> Adding CI files is great, and should also come ahead of any stylistic changes.

Done in #30.

> In this case, I don't see much benefit to dropping support for older nodes before making the fix in 4e1a906, especially since that would mean that tap 10 and earlier could never pull in this fix.
>
> Please rebase 4e1a906 onto current master, with current master's style. That is a good bugfix which should be applied as a patch release asap.

See #31. It's still based on #30 which fixes CI.

**Pull request closed without merging**
